import PageHero from "../components/PageHero";
import type { Metadata } from "next";
import Link from "next/link";
import { firm } from "../lib/firm";
export const metadata: Metadata = { title: "Our People", description: "Meet Jerry Edemeka, lead partner, and the supporting partners of Alpha-Juris Chambers." };
const people = [
  { name: "George C. Adiele", initials: "GA", role: "Founder & Managing Partner", office: "Lagos", bio: "Called to the Nigerian Bar in 1986, George C. Adiele founded Alpha-Juris Chambers in 1992. His earlier experience at International Merchant Bank included international financing, loan syndication and equipment leasing. He leads the firm’s practice in Lagos and its environs.", focus: "Commercial practice · Banking & finance" },
  { name: "Chijioke H. Orji", initials: "CO", role: "Managing Partner", office: "Abuja", bio: "Chijioke H. Orji was called to the Bar in 1991 and leads the firm’s Abuja practice. His experience spans corporate law, general investment and real estate. He is the founder and Chairman of the Lawquest Group and a member of the Nigerian Bar Association and International Bar Association.", focus: "Corporate law · Investment · Real estate" },
  { name: "Chris Chikezie Okoro", initials: "CC", role: "Managing Partner", office: "Port Harcourt & Calabar", bio: "A graduate of the University of Nigeria, Chris Chikezie Okoro worked in private practice and the legal department of Pan African Bank before joining Alpha-Juris Chambers in 1996. He leads the firm’s practice in Port Harcourt and Calabar and is a member of the Nigerian Bar Association and Chartered Institute of Arbitrators.", focus: "Legal advisory · Dispute resolution" },

];
export default function AttorneysPage() {
  return <>
    <PageHero eyebrow="Our people" title="Personal leadership." accent="Collective experience." description="Led by Jerry Edemeka, our practice brings together experienced partners to support clients across litigation, corporate matters and investment." />
    <section className="site-container lead-partner" id="jerry-edemeka" aria-labelledby="jerry-name">
      <div className="lead-partner-intro"><p className="eyebrow">Meet our lead partner</p><div className="lead-monogram" aria-hidden>JE</div><h2 id="jerry-name">Jerry Edemeka</h2><p className="person-role">Lead Partner · Abuja</p><p className="lead-focus">Litigation & Dispute Resolution<br />Corporate Tax Management Consultancy</p><a className="button-navy" href={`mailto:${firm.partnerEmail}`}>Contact Jerry directly <span aria-hidden>↗</span></a><a className="lead-email" href={`mailto:${firm.partnerEmail}`}>{firm.partnerEmail}</a></div>
      <div className="lead-partner-bio"><p className="eyebrow">Experience & background</p><h3>Experienced advocacy.<br />Considered commercial advice.</h3><p>Jerry Edemeka leads the practice, supported by partners whose experience spans commercial law, investment and dispute resolution.</p><p>A graduate of the University of Calabar, Jerry obtained his LL.B. in 1991 and was called to the Nigerian Bar in 1992. He joined Alpha-Juris Chambers in January 2000 following experience as State Counsel in the Ministry of Justice, Rivers State, during his national service, and as an associate in private practice.</p><p>His areas of practice include litigation and corporate tax management consultancy. He is a Director of Lawquest Limited and a member of the editorial board of Lawquest Publishing Company Limited.</p><dl className="lead-credentials"><div><dt>Called to the Bar</dt><dd>1992 · Nigeria</dd></div><div><dt>Joined the firm</dt><dd>January 2000</dd></div><div><dt>Professional memberships</dt><dd>Nigerian Bar Association<br />Chartered Institute of Taxation of Nigeria</dd></div></dl><Link className="text-link" href="/contact">Arrange a consultation <span aria-hidden>↗</span></Link></div>
    </section>
    <section className="supporting-partners" aria-labelledby="supporting-title"><div className="site-container supporting-heading"><p className="eyebrow">The wider team</p><h2 className="editorial-title" id="supporting-title">Supporting partners.</h2><p className="section-description">Working alongside Jerry, our partners contribute experience across the firm’s practice areas and offices.</p></div><div className="site-container people-grid supporting-grid">{people.map(p=><article className="person-card" key={p.name}><div className="person-top"><span className="person-monogram" aria-hidden>{p.initials}</span><span className="eyebrow">{p.office}</span></div><h3>{p.name}</h3><p className="person-role">{p.role}</p><p className="person-bio">{p.bio}</p><p className="person-focus">{p.focus}</p><Link className="text-link" href="/contact">Contact the firm <span aria-hidden>↗</span></Link></article>)}</div></section>
    <section className="site-container conversation-section"><div><p className="eyebrow">Work with us</p><h2>The right conversation.<br />A clearer way forward.</h2></div><Link href="/contact" className="button-navy">Discuss your matter <span aria-hidden>↗</span></Link></section>
  </>;
}
