"use client";
import { useState } from "react";
import { books } from "../lib/publications";
import { firm } from "../lib/firm";
export default function PublicationLibrary() {
  const [query,setQuery] = useState("");
  const visible = books.filter(book=>`${book.title} ${book.category} ${book.summary} ${book.highlights.join(" ")}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <section className="site-container library-section"><div className="library-toolbar"><div><p className="eyebrow">Publication catalogue</p><h2 className="editorial-title">Knowledge for practice.</h2></div><label className="library-search">Search publications<input type="search" placeholder="Search by title or topic…" value={query} onChange={e=>setQuery(e.target.value)} /></label></div><p className="result-count" role="status">{visible.length} {visible.length===1 ? "publication" : "publications"}{query.trim() ? " matching your search" : " in the catalogue"}</p><div className="publication-grid">{visible.map(book=><article className="publication-card" key={book.title}><p className="eyebrow">{book.category}</p><h3>{book.title}</h3><p>{book.summary}</p><details><summary>Topics covered <span aria-hidden>+</span></summary><ul>{book.highlights.map(item=><li key={item}>{item}</li>)}</ul></details><a className="text-link" href={`mailto:${firm.email}?subject=${encodeURIComponent(`Publication enquiry: ${book.title}`)}&body=${encodeURIComponent(`Hello Alpha-Juris Chambers,\n\nI would like information on availability, edition, format and price for:\n${book.title}\n\nMy name:\nPreferred format:\nLocation:\n\nThank you.`)}`}>Enquire about this title <span aria-hidden>↗</span></a></article>)}</div>{visible.length===0 && <div className="empty-state"><h3>No matching publications.</h3><p>Try a broader topic such as property, finance or litigation.</p><button className="button-navy" onClick={()=>setQuery("")}>Clear search <span aria-hidden>↗</span></button></div>}<p className="catalogue-note">Enquiries open a draft in your email app. Please ask our team about the current edition, availability, format and price before ordering.</p></section>;
}
