import type { Metadata } from "next";
import Link from "next/link";
import PageHero from "../components/PageHero";
import ContactCallout from "../components/ContactCallout";
export const metadata: Metadata = { title: "About the Firm", description: "Established in 1992, Alpha-Juris Chambers advises clients across commercial law, dispute resolution and investment, with offices in four Nigerian cities." };
export default function AboutPage() {
  return <>
    <PageHero eyebrow="About the firm" title="Grounded in experience." accent="Guided by your objectives." description="Alpha-Juris Chambers is a Nigerian legal practice built on honesty, integrity and excellence. Our purpose is to help clients pursue their business and personal objectives with clear, considered legal advice." />
    <section className="site-container about-intro"><div><p className="eyebrow">Our story</p><h2 className="editorial-title">A firm foundation.<br />A wider perspective.</h2><div className="about-facts"><div><strong>1992</strong><span>Year established</span></div><div><strong>04</strong><span>Nigerian office locations</span></div></div></div><div className="prose"><p>Alpha-Juris Chambers was established in 1992. From its beginnings as a single-office practice, the firm has grown to serve clients through offices in Lagos, Port Harcourt, Calabar and Abuja.</p><p>Our work spans commercial transactions, corporate advisory, litigation and alternative dispute resolution. We advise businesses, investors and individuals whose needs range from a specific legal issue to ongoing support across their activities.</p><p>Under Jerry Edemeka’s leadership, supported by the wider partner team, we bring legal experience and a practical understanding of our clients’ objectives to each matter.</p><Link className="text-link" href="/attorneys#jerry-edemeka">Meet our lead partner <span aria-hidden>↗</span></Link></div></section>
    <section className="values-section"><div className="site-container"><div className="section-heading"><div><p className="eyebrow">What guides us</p><h2>Principles behind the practice.</h2></div></div><div className="values-grid">{[["01","Honesty","Clear advice begins with a candid assessment of your circumstances, the options available and the issues that need attention."],["02","Integrity","Professional responsibility and careful judgment guide how we approach each client relationship and every matter entrusted to us."],["03","Excellence","We combine legal analysis, preparation and attention to detail in pursuit of our clients’ objectives."]].map(([number,title,text])=><article key={title}><span className="practice-number">{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="site-container about-approach"><div><p className="eyebrow">Our approach</p><h2 className="editorial-title">Understand the objective.<br />Consider the options.<br />Act with purpose.</h2></div><div className="prose"><p>We begin with what you want to achieve. That understanding informs the advice, documentation and representation we provide, whether the matter concerns an investment, a business transaction or a dispute.</p><p>In contentious matters, our practice considers alternative dispute resolution alongside litigation. The appropriate approach depends on the circumstances and the client’s priorities.</p><Link className="text-link" href="/practice-areas">Explore our expertise <span aria-hidden>↗</span></Link></div></section>
    <section className="heritage-section"><div className="site-container heritage-layout"><div><p className="eyebrow light">Beyond the brief</p><h2 className="editorial-title">A tradition of<br />sharing legal knowledge.</h2></div><div><p>The firm’s history includes seminars, workshops and legal education on commercial and investment matters.</p><p>A paper presented by Sotonye I. Etomi records the Alpha Juris Workshop Series held in Port Harcourt on 6–7 February 2003, addressing the legal perspective on public offers of company securities.</p><a className="text-link light" href="https://nigerianlawguru.com/wp-content/uploads/2024/06/PUBLIC-OFFER-OF-COMPANY-SECURITIES.pdf" target="_blank" rel="noopener noreferrer">View the historical workshop paper <span aria-hidden>↗</span></a><span className="source-caption">Historical reference · February 2003 · External PDF</span></div></div></section>
    <section className="site-container offices-section"><div className="section-heading"><div><p className="eyebrow">Our presence</p><h2>Four cities. A shared commitment.</h2></div><Link className="text-link" href="/contact">Office & contact details <span aria-hidden>↗</span></Link></div><div className="office-cities">{["Abuja","Lagos","Port Harcourt","Calabar"].map((city,i)=><div key={city}><span>0{i+1}</span><h3>{city}</h3></div>)}</div></section>
    <ContactCallout />
  </>;
}
